import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Calculates the closest supported aspect ratio for the Gemini API.
 */
const getClosestAspectRatio = (width: number, height: number): "1:1" | "3:4" | "4:3" | "9:16" | "16:9" => {
  const targetRatio = width / height;
  const supportedRatios: { value: "1:1" | "3:4" | "4:3" | "9:16" | "16:9"; ratio: number }[] = [
    { value: "1:1", ratio: 1.0 },
    { value: "3:4", ratio: 0.75 },
    { value: "4:3", ratio: 1.333 },
    { value: "9:16", ratio: 0.5625 },
    { value: "16:9", ratio: 1.777 },
  ];

  return supportedRatios.reduce((prev, curr) => {
    return Math.abs(curr.ratio - targetRatio) < Math.abs(prev.ratio - targetRatio) ? curr : prev;
  }).value;
};

/**
 * Transfers color from source image to reference image.
 * 
 * @param referenceImageBase64 Base64 string of the target shape/texture image
 * @param referenceMimeType Mime type of reference image
 * @param sourceImageBase64 Base64 string of the color source image
 * @param sourceMimeType Mime type of source image
 * @param refWidth Width of the reference image
 * @param refHeight Height of the reference image
 * @returns The generated image as a base64 string
 */
export const transferTowelColor = async (
  referenceImageBase64: string,
  referenceMimeType: string,
  sourceImageBase64: string,
  sourceMimeType: string,
  refWidth: number,
  refHeight: number
): Promise<string> => {
  try {
    // We clean the base64 strings just in case they contain the data URL prefix
    const cleanRef = referenceImageBase64.replace(/^data:image\/\w+;base64,/, "");
    const cleanSource = sourceImageBase64.replace(/^data:image\/\w+;base64,/, "");

    const closestAspectRatio = getClosestAspectRatio(refWidth, refHeight);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `Instruction: You are an expert image editor.
            
            Image 1 (First Image provided) is the "Reference Image".
            Image 2 (Second Image provided) is the "Source Style".
            
            Task: Create a new image that is a pixel-perfect reconstruction of the Reference Image, but with the specific object (the towel) having the color and fabric pattern of the Source Style.
            
            STRICT GUIDELINES:
            1. **NO CROPPING**: The output MUST have the exact same composition and framing as the Reference Image. Do not zoom in or cut off any part of the original scene.
            2. **PRESERVE BACKGROUND**: The background, floor, walls, and lighting must remain exactly identical to the Reference Image.
            3. **FULL OBJECT**: Ensure the entire towel from the Reference Image is visible.
            4. **COLOR TRANSFER**: Apply the texture and color from Image 2 onto the towel in Image 1.
            
            Output only the resulting image.`
          },
          {
            inlineData: {
              mimeType: referenceMimeType,
              data: cleanRef
            }
          },
          {
            inlineData: {
              mimeType: sourceMimeType,
              data: cleanSource
            }
          }
        ]
      },
      config: {
        imageConfig: {
            aspectRatio: closestAspectRatio
        }
      }
    });

    // Check for image in response
    if (response.candidates && response.candidates.length > 0) {
      const candidate = response.candidates[0];
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to process image: ${error.message}`);
    }
    throw new Error("An unexpected error occurred while communicating with Gemini.");
  }
};
